### ISSUE TITLE
Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by edheltzel** [nirgn975/generator-jekyll-starter-kit#74]
Was getting the below:
```shell
npm run gulp

> epluno@1.0.0 gulp /Users/ed/Sites/epluno
> gulp

[08:35:09] Requiring external module babel-register
[08:35:10] Using gulpfile ~/Sites/epluno/gulpfile.babel.js
[08:35:10] Task 'default' is not in your gulpfile
[08:35:10] Please check the documentation for proper gulpfile formatting
```

I run `npm install --save-dev babel-register` resolved the default task error but running `npm run gulp` starts and finishes after almost no time...

**Comment by nirgn975** [comment]
@ginfuru Can you try to run `npm run gulp serve` ?

**Comment by nirgn975** [comment]
I think it's a `jekyll` issue.
Try to install jekyll (`gem install jekyll`) and then run again `npm run gulp serve`.

**Comment by edheltzel** [comment]
@nirgn975  No luck - same [error ](https://gist.github.com/ginfuru/8fb225a701d099b604ede1a290b0e175)
