### ISSUE TITLE
Why tell the user to run bower install when there is no bower file exists?

### ISSUE THREAD

**Issue by RoySegall** [nirgn975/generator-jekyll-starter-kit#76]
After the project was generated the CLI wrote to run `bower install` but there is not`bower.json` file. Is there a special reason or it's removable?

**Comment by nirgn975** [comment]
Oh, I didn't know I'm doing it. I think it's from the upgrade to Yeoman 1.0. Want to take this one? (;

**Comment by RoySegall** [comment]
More issues:
`npm run gulp` gives me

> [10:59:18] Requiring external module babel-register
> [10:59:19] Using gulpfile /Applications/MAMP/htdocs/nuntius-doc/gulpfile.babel.js
> [10:59:19] Task 'default' is not in your gulpfile
> [10:59:19] Please check the documentation for proper gulpfile formatting
> 
> npm ERR! Darwin 16.5.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! nuntius-doc@1.0.0 gulp: `gulp`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the nuntius-doc@1.0.0 gulp script 'gulp'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the nuntius-doc package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nuntius-doc
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls nuntius-doc
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Applications/MAMP/htdocs/nuntius-doc/npm-debug.log

And this is the `npm-debug.log` - https://gist.github.com/RoySegall/2169eac7732bcdc98fe18b225f4fdcf9

2. When running `gulp serve` I'm getting:
<img width="1587" alt="nuntius-doc" src="https://cloud.githubusercontent.com/assets/1222368/25694984/ec60ab34-30b9-11e7-9bd1-ec817c44fc68.png">
<img width="481" alt="nuntius-doc" src="https://cloud.githubusercontent.com/assets/1222368/25694997/fa25ca92-30b9-11e7-8370-62c9f104a538.png">
And the console log:

> 
> main.css Failed to load resource: the server responded with a status of 404 (Not Found)
> localhost/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
> main.css Failed to load resource: the server responded with a status of 404 (Not Found)

3. The project is set to support 3.1.3 but when installing jekyll we get 3.4.3. Change that in the Gemfile fixed it.

**Comment by edheltzel** [comment]
@RoySegall You'll need to update your `_config.yml`  and change to
```json
baseurl:"""
```
to fix the CSS path issue. 

You should also check the **Gemfile**  and update `gem "jekyll", "3.3.1"` to the version of Jekyll you currently have installed. 
For me I run the latest Jekyll version
```json
gem "jekyll", "3.4.3"
```
After you edit the **Gemfile** you'll need to run `bundle install` 
I discovered this in issue #74
